version: '3.8'

services:
  app:
    image: ajithkrkd/ecommerce-test:1.0.1
    ports:
      - 9000:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/trial?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    volumes:
      - image_data:/opt/src/main/resources/static/uploads/
  db:
    image: mysql
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trial
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    external: true
  image_data:
    external: true