spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password#2#2
    url: jdbc:mysql://localhost:3309/test
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      format_sql: true
    show-sql: true